steps:
  - name: 'gcr.io/cloud-builders/git'
    args:
      - submodule
      - init
  - name: 'gcr.io/cloud-builders/git'
    args:
      - submodule
      - update
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - gcr.io/kimthi/github.com/lehoanglong/kim_thi_frontend_user:$COMMIT_SHA
      - .
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '-image', 'gcr.io/kimthi/github.com/lehoanglong/kim_thi_frontend_user:$COMMIT_SHA']
      