steps:
  - name: 'gcr.io/cloud-builders/git'
    secretEnv: ['SSH_KEY']
    entrypoint: 'bash'
    args:
      - -c
      - |
        echo "$$SSH_KEY" >> /root/.ssh/id_rsa
        chmod 400 /root/.ssh/id_rsa
        cp known_hosts.github /root/.ssh/known_hosts
    volumes:
      - name: 'ssh'
        path: /root/.ssh
  - name: 'gcr.io/cloud-builders/git'
    args:
      - submodule
      - init
    volumes:
      - name: 'ssh'
        path: /root/.ssh
  - name: 'gcr.io/cloud-builders/git'
    args:
      - submodule
      - update
    volumes:
      - name: 'ssh'
        path: /root/.ssh
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - gcr.io/kimthi/github.com/lehoanglong/kim_thi_frontend_user:$COMMIT_SHA
      - .
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '-image', 'gcr.io/kimthi/github.com/lehoanglong/kim_thi_frontend_user:$COMMIT_SHA']
      