FROM node:17.6-buster

WORKDIR /usr/src/app

COPY . .

ARG BACKEND_URL_FROM_BROWSER
ARG ECOMMERCE_GA_TRACKING_ID

ENV NEXT_PUBLIC_BACKEND_URL_FROM_BROWSER=$BACKEND_URL_FROM_BROWSER
ENV NEXT_PUBLIC_ECOMMERCE_GA_TRACKING_ID=$ECOMMERCE_GA_TRACKING_ID

RUN npm install

RUN npm run build

CMD npm start
