export const Symbols = {
    PRODUCT_REPOSITORY: Symbol.for("PRODUCT_REPOSITORY"),
    CART_REPOSITORY: Symbol.for("CART_REPOSITORY"),
    CART_CONTROLLER: Symbol.for("CART_CONTROLLER"),
    ADDRESS_REPOSITORY: Symbol.for("ADDRESS_REPOSITORY"),
    GEOCODING_SERVICE: Symbol.for("GEOCODING_SERVICE"),
    SHIPPING_FEE_REPOSITORY: Symbol.for("SHIPPING_FEE_REPOSITORY"),
    ORDER_REPOSITORY: Symbol.for("ORDER_REPOSITORY"),
    PRICE_REQUEST_REPOSITORY: Symbol.for('PRICE_REQUEST_REPOSITORY'),
}

export default Symbols;
